//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public int IdAsignatura { get; set; }
        public string Asignatura1 { get; set; }
        public int IdCarrera { get; set; }
        public int Semestre { get; set; }
    
        public virtual Carrera Carrera { get; set; }
    }
}
